name = "RezvanGrad"
uuid = "a123b456-c789-4567-89ab-cdef01234567"
authors = ["Reza Rezvan <reza@rezvan.xyz>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"
Plots = "1.25"
GraphRecipes = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
